### ISSUE TITLE
sticky left column

### ISSUE THREAD

**Issue by vipulasri** [brkckr/TableView#1]
Great work for this kind of view. Is this possible to have left column sticky as well?

**Comment by brkckr** [comment]
Thanks.

This is just a small sample. I cant implement that bu you can look at the more complex libraries like [Evren's TableView.](https://github.com/evrencoskun/TableView)

I got an idea which is not perfect. In this example, there is 1 header and 1 RecyclerView. We can make it looks like sticky with 2 headers and 2 RecyclerViews. The header and the RecyclerView on the left show the information of the sticky column. The header and the ReyclerView on the right show the rest of the table.

I thought I could not tell you well, I drew the picture, added below.

RecyclerView on the right(RecyclerView2) must be scrollable both horizontal and vertical at the same time. So it should be as I did in the my sample. On the other hand, RecyclerView on the left(RV1) just shows only one item per row. The important point here is that when moving the RecyclerView2, header2 should move right and left and rv1 should move up and down. I hope you understand :)

![img_20180502_191147](https://user-images.githubusercontent.com/14269947/39536116-580f6b52-4e3e-11e8-84ed-4912347ccf14.jpg)
